services:
  idp-service:
    build:
      context: .
      dockerfile: Web.IdP/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_PROVIDER=${DATABASE_PROVIDER:-SqlServer}
      - ConnectionStrings__SqlServerConnection=${ConnectionStrings__SqlServerConnection:-Server=mssql-service;Database=HybridAuthIdP;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True}
      - ConnectionStrings__PostgreSqlConnection=${ConnectionStrings__PostgreSqlConnection:-Host=postgres-service;Database=hybridauth_idp;Username=user;Password=password}
      - ConnectionStrings__Redis=${ConnectionStrings__Redis:-redis-service:6379}
    depends_on:
      mssql-service:
        condition: service_started
      postgres-service:
        condition: service_started
      redis-service:
        condition: service_started
  
  mssql-service:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
  
  postgres-service:
    image: postgres:17
    environment:
      POSTGRES_DB: hybridauth_idp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  redis-service:
    image: redis:alpine
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI
    environment:
      MP_MAX_MESSAGES: 5000


volumes:
  mssql-data:
  postgres-data: